name: release

on:
  push:
    tags:
      - "*"

env:
  PDM_VERSION: "2.4.9"
  PYTHON_VERSION: "3.8"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PDM & Python
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          version: ${{ env.PDM_VERSION }}

      - name: Install dependencies
        run: |
          pdm export -o requirements.txt --without-hashes
          pip install -r requirements.txt

      - name: Build dist
        run: python -m build . --sdist

      - name: Save dist as artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-dist
          path: ./dist/*

      - name: Release package
        env:
          PDM_PUBLISH_USERNAME: "__token__"
          PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: pdm publish --no-build
