name: test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

env:
  PDM_VERSION: "2.4.9"
  PYTHON_VERSION: "3.8"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PDM & Python
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          version: ${{ env.PDM_VERSION }}

      - name: Install dependencies
        run: |
          pdm export -o requirements.txt --without-hashes
          pip install -r requirements.txt

      - name: Run lint
        run: pre-commit run --all

  test:
    strategy:
      matrix:
        py_version: [ "3.8", "3.9", "3.10", "3.11" ]
        os: [ ubuntu-latest ]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3

      - name: Setup PDM & Python
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "${{ matrix.py_version }}"
          version: ${{ env.PDM_VERSION }}

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          pdm export -o requirements.txt --without-hashes
          pip install -r requirements.txt

      - name: Build extension
        run: make build-extension

      - name: Run tests
        run: make test
